import { TITLE_TEXT, SUBTITLE_TEXT, Palette } from "./constants";
import { Anim } from "./types";

export const animations: Anim[] = [
  {
    id: "title",
    type: "text",
    text: TITLE_TEXT,
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 0,
    maxWidth: "full",
    offsetX: { start: 0, end: 0 },
    offsetY: { start: 50, end: 0 },
    kerning: { start: 40, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 8, y: 8, size: 16 },
    stroke: { width: 16, color: Palette.Black },
  },
  {
    id: "subtitle",
    type: "text",
    text: SUBTITLE_TEXT,
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 12,
    maxWidth: "title",
    offsetX: { start: 0, end: 0 },
    offsetY: { start: 50, end: 0 },
    kerning: { start: 0, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
    stroke: { width: 8, color: Palette.Black },
  },
  {
    id: "card",
    type: "sprite",
    progress: 0,
    frame: 0,
    currentFrame: 0,
    speed: 6,
    frames: [
      { x: 0, y: 4992 },
      { x: 64, y: 4992 },
      { x: 128, y: 4992 },
      { x: 0, y: 3744 },
      { x: 64, y: 3744 },
      { x: 128, y: 3744 },
      { x: 64, y: 3744, flipX: true },
      { x: 0, y: 3744, flipX: true },
      { x: 128, y: 4992, flipX: true },
      { x: 64, y: 4992, flipX: true },
      { x: 0, y: 4992 },
      { x: 64, y: 4992 },
      { x: 128, y: 4992 },
      { x: 0, y: 2496 },
      { x: 64, y: 2496 },
      { x: 128, y: 2496 },
      { x: 64, y: 2496, flipX: true },
      { x: 0, y: 2496, flipX: true },
      { x: 128, y: 4992, flipX: true },
      { x: 64, y: 4992, flipX: true },
    ],
    fadeInDelay: 24,
    maxWidth: "full",
    opacity: { start: 0, end: 1 },
    offsetX: { start: 0, end: 0 },
    offsetY: { start: 50, end: 0 },
  },
];

