import {
  TITLE_TEXT,
  SUBTITLE_TEXT,
  Palette,
  SANS_SERIF_FONT,
  DISPLAY_FONT,
} from "./constants";
import { Anim } from "./types";

export const titleAnimation: Anim[] = [
  {
    id: "title",
    type: "text",
    text: TITLE_TEXT,
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 0,
    maxWidth: "full",
    fontSize: 6,
    position: "center",
    fontFamily: DISPLAY_FONT,
    lineHeight: 1.2,
    slideX: { start: 0, end: 0 },
    slideY: { start: 50, end: 0 },
    kerning: { start: 40, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 8, y: 8, size: 16 },
    stroke: { width: 16, color: Palette.Black },
  },
  {
    id: "subtitle",
    type: "text",
    text: SUBTITLE_TEXT,
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 12,
    maxWidth: "title",
    fontSize: 6,
    position: "center",
    fontFamily: DISPLAY_FONT,
    lineHeight: 1.2,
    slideX: { start: 0, end: 0 },
    slideY: { start: 50, end: 0 },
    kerning: { start: 0, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
    stroke: { width: 8, color: Palette.Black },
  },
  {
    id: "start",
    type: "text",
    text: "!start",
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 32,
    maxWidth: "full",
    fontSize: 1,
    fontFamily: SANS_SERIF_FONT,
    lineHeight: 1.2,
    position: "bottom",
    slideX: { start: 0, end: 0 },
    slideY: { start: 50, end: 0 },
    kerning: { start: 0, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
    stroke: { width: 6, color: Palette.Black },
  },
  {
    id: "card",
    type: "loop",
    progress: 0,
    frame: 0,
    currentFrame: 0,
    speed: 6,
    frames: [
      { x: 0, y: 4992 },
      { x: 64, y: 4992 },
      { x: 128, y: 4992 },
      { x: 0, y: 3744 },
      { x: 64, y: 3744 },
      { x: 128, y: 3744 },
      { x: 64, y: 3744, flipX: true },
      { x: 0, y: 3744, flipX: true },
      { x: 128, y: 4992, flipX: true },
      { x: 64, y: 4992, flipX: true },
      { x: 0, y: 4992 },
      { x: 64, y: 4992 },
      { x: 128, y: 4992 },
      { x: 0, y: 2496 },
      { x: 64, y: 2496 },
      { x: 128, y: 2496 },
      { x: 64, y: 2496, flipX: true },
      { x: 0, y: 2496, flipX: true },
      { x: 128, y: 4992, flipX: true },
      { x: 64, y: 4992, flipX: true },
    ],
    fadeInDelay: 24,
    maxWidth: "full",
    opacity: { start: 0, end: 1 },
    offsetX: { start: 0, end: 0 },
    offsetY: { start: 50, end: 0 },
  },
];

export const bustedAnimation: Anim[] = [
  {
    id: "title",
    type: "text",
    text: "Busted!",
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 0,
    maxWidth: "full",
    fontSize: 6,
    position: "center",
    fontFamily: DISPLAY_FONT,
    lineHeight: 1.2,
    slideX: { start: 0, end: 0 },
    slideY: { start: 50, end: 0 },
    kerning: { start: 40, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 8, y: 8, size: 16 },
    stroke: { width: 16, color: Palette.Black },
  },
  {
    id: "subtitle",
    type: "text",
    text: "Better luck next time!",
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 12,
    maxWidth: "title",
    fontSize: 6,
    position: "center",
    fontFamily: DISPLAY_FONT,
    lineHeight: 1.2,
    slideX: { start: 0, end: 0 },
    slideY: { start: 50, end: 0 },
    kerning: { start: 0, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
    stroke: { width: 8, color: Palette.Black },
  },
  {
    id: "start",
    type: "text",
    text: "!restart",
    color: Palette.Yellow,
    progress: 0,
    fadeInDelay: 32,
    maxWidth: "full",
    fontSize: 1,
    fontFamily: SANS_SERIF_FONT,
    lineHeight: 1.2,
    position: "bottom",
    slideX: { start: 0, end: 0 },
    slideY: { start: 50, end: 0 },
    kerning: { start: 0, end: 0 },
    shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
    stroke: { width: 6, color: Palette.Black },
  },
  {
    id: "card",
    type: "loop",
    progress: 0,
    frame: 0,
    currentFrame: 0,
    speed: 6,
    frames: [
      { x: 0, y: 4992 },
      { x: 64, y: 4992 },
      { x: 128, y: 4992 },
      { x: 0, y: 3744 },
      { x: 64, y: 3744 },
      { x: 128, y: 3744 },
      { x: 64, y: 3744, flipX: true },
      { x: 0, y: 3744, flipX: true },
      { x: 128, y: 4992, flipX: true },
      { x: 64, y: 4992, flipX: true },
      { x: 0, y: 4992 },
      { x: 64, y: 4992 },
      { x: 128, y: 4992 },
      { x: 0, y: 2496 },
      { x: 64, y: 2496 },
      { x: 128, y: 2496 },
      { x: 64, y: 2496, flipX: true },
      { x: 0, y: 2496, flipX: true },
      { x: 128, y: 4992, flipX: true },
      { x: 64, y: 4992, flipX: true },
    ],
    fadeInDelay: 24,
    maxWidth: "full",
    opacity: { start: 0, end: 1 },
    offsetX: { start: 0, end: 0 },
    offsetY: { start: 50, end: 0 },
  },
];

