import { Palette, IMAGE, FONT } from "./constants";
import {
  TextEntityOld,
  AnimatedSpriteEntity,
  SpriteEntity,
  LAYER,
  TimerEntityProps,
  TextEntityProps,
} from "./types";
import { rgb } from "./utils";

const SPRITE_WIDTH = 256;
const SPRITE_HEIGHT = 384;

export const titleScreen: [
  AnimatedSpriteEntity,
  TextEntityProps,
  TextEntityProps,
  TextEntityOld,
] = [
  {
    id: "flip-card",
    type: "animated-sprite",
    src: IMAGE.CARDS,
    playback: "loop",
    layer: LAYER.GAME,
    easing: "easeOutQuint",
    position: "center",
    spriteElapsed: 0,
    spriteDuration: 6,
    spriteIndex: 0,
    sprites: [
      { x: 0, y: 4992 },
      { x: 256, y: 4992 },
      { x: 512, y: 4992 },
      { x: 3072, y: 0 },
      { x: 3328, y: 0 },
      { x: 3584, y: 0 },
      { x: 3328, y: 0, flipX: true },
      { x: 3072, y: 0, flipX: true },
      { x: 512, y: 4992, flipX: true },
      { x: 256, y: 4992, flipX: true },
      { x: 0, y: 4992 },
      { x: 256, y: 4992 },
      { x: 512, y: 4992 },
      { x: 2048, y: 0 },
      { x: 2304, y: 0 },
      { x: 2560, y: 0 },
      { x: 2304, y: 0, flipX: true },
      { x: 2048, y: 0, flipX: true },
      { x: 512, y: 4992, flipX: true },
      { x: 256, y: 4992, flipX: true },
    ],
    spriteWidth: SPRITE_WIDTH,
    spriteHeight: SPRITE_HEIGHT,
    delay: 24,
    translateY: { start: 200, end: 0 },
    opacity: { start: 0, end: 1 },
    float: { x: 0, y: 5, speed: 1 / 2 },
    shadow: {
      color: Palette.DarkestGreen,
      opacity: 1,
      offsetX: 48,
      offsetY: 48,
      blur: 0,
    },
  },
  {
    id: "title",
    type: "text",
    text: "ChatJack",
    layer: LAYER.GAME,
    position: "eyeline",
    fontSize: 128,
    fontFamily: FONT.DISPLAY,
    textBaseline: "top",
    textAlign: "center",
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 6,
    shadowOffsetY: 6,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 5,
    phases: [
      {
        name: "fade-slide-kerning-in-bottom",
        duration: 2,
      },
      {
        name: "float-y",
        duration: 10,
        loop: true,
      },
    ],
  },
  {
    id: "subtitle",
    type: "text",
    text: "Twitch Chat Plays Blackjack",
    layer: LAYER.GAME,
    position: "eyeline",
    fontSize: 40,
    fontFamily: FONT.DISPLAY,
    textBaseline: "top",
    textAlign: "center",
    delay: 12,
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 6,
    shadowOffsetY: 6,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 5,
    phases: [
      {
        name: "fade-slide-in-bottom",
        duration: 2,
      },
      {
        name: "float-y",
        duration: 10,
        loop: true,
      },
    ],
  },
  {
    id: "start",
    type: "text-old",
    text: "!start",
    easing: "easeOutCubic",
    layer: LAYER.GAME,
    delay: 32,
    offsetY: -0.1,
    style: {
      color: Palette.Yellow,
      maxWidth: "full",
      fontSize: 24,
      fontFamily: FONT.SANS_SERIF,
      lineHeight: 1,
      shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
      stroke: { width: 6, color: Palette.Black },
    },
    position: "bottom",
    translateY: { start: 50, end: 0 },
    opacity: { start: 0, end: 1 },
    float: { x: 0, y: 2, speed: 1 / 6 },
    index: 2,
  },
];

export const gameoverText: [TextEntityOld, TextEntityOld, TextEntityOld] = [
  {
    id: "title",
    type: "text-old",
    text: "Dealer Win!",
    easing: "easeOutCubic",
    layer: LAYER.GAME,
    style: {
      color: Palette.Yellow,
      maxWidth: "full",
      fontSize: 100,
      fontFamily: FONT.DISPLAY,
      lineHeight: 1.2,
      shadow: { color: Palette.DarkestGreen, x: 8, y: 8, size: 16 },
      stroke: { width: 16, color: Palette.Black },
    },
    position: "eyeline",
    translateY: { start: 50, end: 0 },
    opacity: { start: 0, end: 1 },
    kerning: { start: 40, end: 0 },
    float: { x: 0, y: 3, speed: 1 / 6 },
    index: 0,
  },
  {
    id: "subtitle",
    type: "text-old",
    text: "Better luck next time",
    easing: "easeOutCubic",
    layer: LAYER.GAME,
    delay: 12,
    offsetY: 0.025,
    style: {
      color: Palette.Yellow,
      maxWidth: "title",
      fontSize: 48,
      fontFamily: FONT.DISPLAY,
      lineHeight: 1.2,
      shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
      stroke: { width: 8, color: Palette.Black },
    },
    position: "eyeline",
    translateY: { start: 50, end: 0 },
    opacity: { start: 0, end: 1 },
    float: { x: 0, y: 3, speed: 1 / 6 },
    index: 1,
  },
  {
    id: "restart",
    type: "text-old",
    text: "!restart",
    easing: "easeOutCubic",
    layer: LAYER.GAME,
    delay: 32,
    offsetY: -0.1,
    style: {
      color: Palette.Yellow,
      maxWidth: "full",
      fontSize: 24,
      fontFamily: FONT.SANS_SERIF,
      lineHeight: 1,
      shadow: { color: Palette.DarkestGreen, x: 4, y: 4, size: 16 },
      stroke: { width: 6, color: Palette.Black },
    },
    position: "bottom",
    translateY: { start: 50, end: 0 },
    opacity: { start: 0, end: 1 },
    float: { x: 0, y: 2, speed: 1 / 6 },
    index: 2,
  },
];

export const actionText: TextEntityOld = {
  id: "action",
  type: "text-old",
  text: "",
  layer: LAYER.GAME,
  easing: "easeOutCubic",
  speed: 1 / 6,
  style: {
    color: Palette.Yellow,
    maxWidth: "full",
    fontSize: 60,
    fontFamily: FONT.SANS_SERIF,
    lineHeight: 1.2,
    shadow: { color: Palette.DarkestGreen, x: 8, y: 8, size: 16 },
    stroke: { width: 16, color: Palette.Black },
  },
  position: "bottom",
  opacity: { start: 0, end: 1 },
  translateY: { start: 50, end: 0 },
  // kerning: { start: 40, end: 0 },
};

export const scoreText: TextEntityProps = {
  id: "score",
  type: "text",
  text: "",
  layer: LAYER.UI,
  position: "bottom left",
  textAlign: "left",
  textBaseline: "top",
  color: rgb(Palette.White),
  fontSize: 32,
  fontFamily: FONT.SANS_SERIF,
  shadowColor: rgb(Palette.DarkestGreen),
  shadowOffsetX: 4,
  shadowOffsetY: 4,
  shadowBlur: 0,
  strokeColor: rgb(Palette.Black),
  strokeWidth: 2,
  phases: [],
};

export const cardSprite: SpriteEntity = {
  id: "default-card",
  type: "sprite",
  src: IMAGE.CARDS,
  easing: "easeOutQuint",
  layer: LAYER.GAME,
  speed: 1 / 12,
  sprites: [{ x: 0, y: 4992 }],
  spriteWidth: SPRITE_WIDTH,
  spriteHeight: SPRITE_HEIGHT,
  shadow: {
    color: Palette.DarkestGreen,
    opacity: 1,
    offsetX: 12,
    offsetY: 12,
    blur: 0,
  },
};

export const animatedCardSprite: AnimatedSpriteEntity = {
  id: "animated-card",
  type: "animated-sprite",
  src: IMAGE.CARDS,
  playback: "once",
  easing: "easeOutQuint",
  layer: LAYER.GAME,
  spriteWidth: SPRITE_WIDTH,
  spriteHeight: SPRITE_HEIGHT,
  spriteElapsed: 0,
  spriteDuration: 1,
  spriteIndex: 0,
  sprites: [
    { x: 0, y: 4992 },
    { x: 256, y: 4992 },
    { x: 512, y: 4992 },
  ],
};

export const turnTimer: TimerEntityProps = {
  id: "turn-timer",
  type: "timer",
  layer: LAYER.GAME,
  position: "top right",
  color: rgb(Palette.White),
  backgroundColor: rgb(Palette.DarkestGreen),
  radius: 24,
  startAngle: 0,
  rotation: -90,
  phases: [
    {
      name: "zoom-in",
      duration: 1,
    },
    {
      name: "countdown",
      duration: 30,
    },
    {
      name: "zoom-out",
      duration: 0.5,
    },
  ],
};
