import { Game } from "@/components/game";
import { pressStart } from "@/lib/fonts";
import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark ${pressStart.variable}`}>{children}</body>
    </html>
  );
}
