import { FONT, IMAGE } from "@/lib/canvas/constants";
import { SpriteEntityProps } from "@/lib/canvas/entity.sprite";
import { TextEntityProps } from "@/lib/canvas/entity.text";
import { TimerEntityProps } from "@/lib/canvas/entity.timer";
import { LAYER, POSITION } from "@/lib/canvas/types";
import { rgb } from "@/lib/canvas/utils";
import { Palette } from "@/lib/constants";

const SPRITE_WIDTH = 256;
const SPRITE_HEIGHT = 384;

export const titleScreen: [
  SpriteEntityProps,
  TextEntityProps,
  TextEntityProps,
  TextEntityProps,
] = [
  {
    id: "flip-card",
    type: "sprite",
    src: IMAGE.CARDS,
    layer: LAYER.GAME,
    position: POSITION.CENTER,
    spriteWidth: SPRITE_WIDTH,
    spriteHeight: SPRITE_HEIGHT,
    opacity: 1,
    phases: [
      {
        name: "fade-slide-in-bottom",
        duration: 2,
      },
      {
        name: "animated-float-y",
        duration: 1.5,
        magnitude: 6,
        loop: true,
      },
    ],
    spriteElapsed: 0,
    spriteDuration: 6,
    scale: 0.7,
    sprites: [
      { x: 0, y: 4992 },
      { x: 256, y: 4992 },
      { x: 512, y: 4992 },
      { x: 3072, y: 0 },
      { x: 3328, y: 0 },
      { x: 3584, y: 0 },
      { x: 3328, y: 0, flipX: true },
      { x: 3072, y: 0, flipX: true },
      { x: 512, y: 4992, flipX: true },
      { x: 256, y: 4992, flipX: true },
      { x: 0, y: 4992 },
      { x: 256, y: 4992 },
      { x: 512, y: 4992 },
      { x: 2048, y: 0 },
      { x: 2304, y: 0 },
      { x: 2560, y: 0 },
      { x: 2304, y: 0, flipX: true },
      { x: 2048, y: 0, flipX: true },
      { x: 512, y: 4992, flipX: true },
      { x: 256, y: 4992, flipX: true },
    ],
    delay: 24,
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 32,
    shadowOffsetY: 32,
    shadowBlur: 0,
  },
  {
    id: "title",
    type: "text",
    text: "ChatJack",
    layer: LAYER.GAME,
    position: POSITION.EYELINE,
    fontSize: 128,
    fontFamily: FONT.DISPLAY,
    textBaseline: "top",
    textAlign: "center",
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 6,
    shadowOffsetY: 6,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 5,
    phases: [
      {
        name: "fade-slide-kerning-in-bottom",
        duration: 2,
      },
      {
        name: "float-y",
        duration: 3,
        magnitude: 3,
        loop: true,
      },
    ],
  },
  {
    id: "subtitle",
    type: "text",
    text: "Twitch Chat Plays Blackjack",
    layer: LAYER.GAME,
    position: POSITION.EYELINE,
    fontSize: 40,
    fontFamily: FONT.DISPLAY,
    textBaseline: "top",
    textAlign: "center",
    delay: 12,
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 6,
    shadowOffsetY: 6,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 5,
    phases: [
      {
        name: "fade-slide-in-bottom",
        duration: 2,
      },
      {
        name: "float-y",
        duration: 2,
        magnitude: 1.5,
        loop: true,
      },
    ],
  },
  {
    id: "start",
    type: "text",
    text: "!start",
    layer: LAYER.GAME,
    position: POSITION.BOTTOM,
    fontSize: 24,
    fontFamily: FONT.SANS_SERIF,
    textBaseline: "middle",
    textAlign: "center",
    delay: 32,
    offsetY: -25,
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 4,
    shadowOffsetY: 4,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 4,
    phases: [
      {
        name: "fade-slide-in-bottom",
        duration: 2,
      },
      {
        name: "float-y",
        duration: 2,
        magnitude: 2,
        loop: true,
      },
    ],
  },
];

export const gameoverText: [TextEntityProps, TextEntityProps, TextEntityProps] =
  [
    {
      id: "title",
      type: "text",
      text: "Dealer Win!",
      layer: LAYER.GAME,
      position: POSITION.EYELINE,
      fontSize: 100,
      fontFamily: FONT.DISPLAY,
      textBaseline: "top",
      textAlign: "center",
      color: rgb(Palette.Yellow),
      shadowColor: rgb(Palette.DarkestGreen),
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowBlur: 0,
      strokeColor: rgb(Palette.Black),
      strokeWidth: 5,
      phases: [
        {
          name: "fade-slide-kerning-in-bottom",
          duration: 2,
        },
        {
          name: "float-y",
          duration: 3,
          magnitude: 3,
          loop: true,
        },
      ],
    },
    {
      id: "subtitle",
      type: "text",
      text: "Better luck next time",
      layer: LAYER.GAME,
      position: POSITION.EYELINE,
      fontSize: 40,
      fontFamily: FONT.DISPLAY,
      textBaseline: "top",
      textAlign: "center",
      delay: 12,
      color: rgb(Palette.Yellow),
      shadowColor: rgb(Palette.DarkestGreen),
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowBlur: 0,
      strokeColor: rgb(Palette.Black),
      strokeWidth: 5,
      phases: [
        {
          name: "fade-slide-in-bottom",
          duration: 2,
        },
        {
          name: "float-y",
          duration: 2,
          magnitude: 1.5,
          loop: true,
        },
      ],
    },
    {
      id: "restart",
      type: "text",
      text: "!restart",
      layer: LAYER.GAME,
      position: POSITION.BOTTOM,
      fontSize: 24,
      fontFamily: FONT.SANS_SERIF,
      textBaseline: "middle",
      textAlign: "center",
      delay: 24,
      offsetY: -25,
      color: rgb(Palette.Yellow),
      shadowColor: rgb(Palette.DarkestGreen),
      shadowOffsetX: 4,
      shadowOffsetY: 4,
      shadowBlur: 0,
      strokeColor: rgb(Palette.Black),
      strokeWidth: 4,
      phases: [
        {
          name: "fade-slide-in-bottom",
          duration: 2,
        },
        {
          name: "float-y",
          duration: 2,
          magnitude: 2,
          loop: true,
        },
      ],
    },
  ];

export const actionText: TextEntityProps = {
  id: "action-text",
  type: "text",
  text: "",
  layer: LAYER.GAME,
  position: POSITION.BOTTOM,
  fontSize: 48,
  fontFamily: FONT.SANS_SERIF,
  textBaseline: "middle",
  textAlign: "center",
  color: rgb(Palette.Yellow),
  shadowColor: rgb(Palette.DarkestGreen),
  shadowOffsetX: 8,
  shadowOffsetY: 8,
  shadowBlur: 0,
  strokeColor: rgb(Palette.Black),
  strokeWidth: 4,
};

export const scoreText: TextEntityProps = {
  id: "score",
  type: "text",
  text: "",
  layer: LAYER.UI,
  position: POSITION.BOTTOM_LEFT,
  textAlign: "left",
  textBaseline: "top",
  color: rgb(Palette.White),
  fontSize: 32,
  fontFamily: FONT.SANS_SERIF,
  shadowColor: rgb(Palette.DarkestGreen),
  shadowOffsetX: 4,
  shadowOffsetY: 4,
  shadowBlur: 0,
  strokeColor: rgb(Palette.Black),
  strokeWidth: 2,
};

export const cardSprite: SpriteEntityProps = {
  id: "default-card",
  type: "sprite",
  src: IMAGE.CARDS,
  layer: LAYER.GAME,
  sprites: [{ x: 0, y: 4992 }],
  spriteWidth: SPRITE_WIDTH,
  spriteHeight: SPRITE_HEIGHT,
  opacity: 1,
  position: POSITION.CENTER,
  scale: 1,
  angle: 0,
  offsetX: 0,
  offsetY: 0,
  shadowColor: rgb(Palette.DarkestGreen),
  shadowOffsetX: 12,
  shadowOffsetY: 12,
  shadowBlur: 0,
};

export const turnTimer: TimerEntityProps = {
  id: "turn-timer",
  type: "timer",
  layer: LAYER.GAME,
  position: POSITION.TOP_RIGHT,
  color: rgb(Palette.White),
  backgroundColor: rgb(Palette.DarkestGreen),
  radius: 24,
  startAngle: 0,
  rotation: -90,
};

export const hitOrStand: [TextEntityProps, TextEntityProps, TextEntityProps] = [
  {
    id: "hit",
    type: "text",
    text: "!hit",
    layer: LAYER.GAME,
    position: POSITION.EYELINE,
    fontSize: 24,
    fontFamily: FONT.SANS_SERIF,
    textBaseline: "top",
    textAlign: "left",
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 4,
    shadowOffsetY: 4,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 2,
    phases: [
      {
        name: "zoom-in",
        duration: 0.5,
      },
      {
        name: "zoom-shake",
        duration: 2,
      },
      {
        name: "float-y",
        duration: 2,
        magnitude: 1.5,
        loop: true,
      },
    ],
  },
  {
    id: "or",
    type: "text",
    text: "or",
    layer: LAYER.GAME,
    position: POSITION.EYELINE,
    fontSize: 24,
    fontFamily: FONT.SANS_SERIF,
    textBaseline: "top",
    textAlign: "center",
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 4,
    shadowOffsetY: 4,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 2,
    phases: [
      {
        name: "zoom-in",
        duration: 0.5,
      },
      {
        name: "float-y",
        duration: 2,
        magnitude: 1.5,
        loop: true,
      },
    ],
  },
  {
    id: "stand",
    type: "text",
    text: "!stand",
    layer: LAYER.GAME,
    position: POSITION.EYELINE,
    fontSize: 24,
    fontFamily: FONT.SANS_SERIF,
    textBaseline: "top",
    textAlign: "right",
    color: rgb(Palette.Yellow),
    shadowColor: rgb(Palette.DarkestGreen),
    shadowOffsetX: 4,
    shadowOffsetY: 4,
    shadowBlur: 0,
    strokeColor: rgb(Palette.Black),
    strokeWidth: 2,
    phases: [
      {
        name: "zoom-in",
        duration: 0.5,
      },
      {
        name: "zoom-shake",
        duration: 2,
      },
      {
        name: "float-y",
        duration: 2,
        magnitude: 1.5,
        loop: true,
      },
    ],
  },
];
